// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyvverexigumbwapaudw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dnZlcmV4aWd1bWJ3YXBhdWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzQ2MDcsImV4cCI6MjA2Mjc1MDYwN30.q6Nuyc4YQ7zPz2v1YgKMfDtf_ZwL9eewnSA_ER0H0po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);